--- 
title: "rechaRge: the HydroBudget model"
author: "Emmanuel Dubois, Yannick Marcon"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: gwrecharge/rechaRge-book
description: "The book presents the rechaRge package, and how it is used with the HydroBudget model."
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(comment="", warning=FALSE, message=FALSE,
                      fig.topcaption=TRUE, fig.path = "fig/")
library(kableExtra)
```

# Welcome {-}

This book provides users with some common workflows for performing groundwater recharge modeling. This book will teach you how to use the [rechaRge](https://github.com/gwrecharge/rechaRge) R package [@R-rechaRge]. This material serves as an online companion for the manuscript “Simulation of long-term spatiotemporal variations in regional-scale groundwater recharge: contributions of a water budget approach in cold and humid climates” [@hess-25-6567-2021].

**HydroBudget** (HB) is a spatially distributed groundwater recharge (GWR) model that computes a superficial water budget on grid cells of regional-scale watersheds with outputs aggregated into monthly time steps and with limited computational time. The model is open-source and was coded in R. This `rechaRge` R package is the result of the effort to make this code reusable and extensible.

This book is organized into different parts. In the _Introduction_, we provide practical information about the `rechaRge` R package. The _Simulation_ part focuses on the **HydroBudget** model that comes with the R package, and how to use the `rechaRge`functions to run simulations, then save and visualize the results. The _Calibration and Sensitivity_ part explores the usage of the `sensitivity` and of the `caRamel` R packages to find and evaluate the "best" sets of model parameters. Finally, the _Extensibility_ section highlights how the generic functions of the `rechaRge` R package can be applied to a different groundwater recharge model.
